import numpy as np
NUM_TIMESTEPS = 150
MAX_DURATION = 1440
OUTPUT_VEL = 40

MIN_VECTOR = np.array([21, 0, 0])
MAX_VECTOR = np.array([108, MAX_DURATION, 1])
RANGE_VECTOR = MAX_VECTOR - MIN_VECTOR

PROCESSED_DATA_DIRNAME = "processed_data/"
TRAIN_DATA_FPATH = PROCESSED_DATA_DIRNAME + "train_data.npy"
PITCH_LABELS_FPATH = PROCESSED_DATA_DIRNAME + "pitch_labels.npy"
DURATION_LABELS_FPATH = PROCESSED_DATA_DIRNAME + "duration_labels.npy"
VEL_LABELS_FPATH = PROCESSED_DATA_DIRNAME + "vel_labels.npy"
TEST_DATA_FPATH = PROCESSED_DATA_DIRNAME + "test_data.npy"